/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./styles/**/*.{css,scss}",
  ],
  theme: {
    extend: {
      screens: {
        xs: "420px",
      },
      colors: {
        "surface-bright": "#363a3c",
        "on-background": "#e0e3e6",
        "on-surface-variant": "#c5c6cd",
        "inverse-primary": "#515f78",
        "on-error": "#690005",
        "primary-container": "#0a192f",
        "tertiary": "#e9c176",
        "outline-variant": "#44474d",
        "on-secondary-container": "#ffdcd7",
        "inverse-on-surface": "#2d3133",
        "on-secondary-fixed-variant": "#930004",
        "primary-fixed": "#d6e3ff",
        "on-primary-fixed": "#0d1c32",
        "on-surface": "#e0e3e6",
        "secondary-container": "#ce0008",
        "surface": "#101416",
        "surface-container-highest": "#323538",
        "on-secondary-fixed": "#410001",
        "surface-tint": "#b9c7e4",
        "surface-dim": "#101416",
        "surface-container-low": "#191c1e",
        "on-secondary": "#690002",
        "primary": "#b9c7e4",
        "on-tertiary-fixed-variant": "#5d4201",
        "secondary-fixed-dim": "#ffb4a9",
        "tertiary-fixed": "#ffdea5",
        "error": "#ffb4ab",
        "secondary-fixed": "#ffdad5",
        "on-primary-fixed-variant": "#39475f",
        "on-tertiary": "#412d00",
        "on-tertiary-container": "#9e7d3a",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#272a2d",
        "outline": "#8f9097",
        "on-primary": "#233148",
        "surface-variant": "#323538",
        "secondary": "#ffb4a9",
        "inverse-surface": "#e0e3e6",
        "tertiary-container": "#231700",
        "tertiary-fixed-dim": "#e9c176",
        "on-tertiary-fixed": "#261900",
        "on-primary-container": "#74829d",
        "surface-container": "#1d2022",
        "surface-container-lowest": "#0b0f11",
        "primary-fixed-dim": "#b9c7e4",
        "error-container": "#93000a",
        "background": "#101416",
        // Equora Brand Colors
        "equoraGold": "#f59e0b",
        "equoraViolet": "#8b5cf6",
        "equoraDark": "#0a192f",
        // Equora Figma Design System
        "equora-bg": "#F0F4F8",
        "equora-blue": "#2563EB",
        "equora-blue-light": "#3B82F6",
        "equora-blue-subtle": "#EFF6FF",
        "equora-blue-border": "#DBEAFE",
        "equora-navy": "#0A1628",
        "equora-navy-dark": "#0F1B35",
        "equora-slate": "#64748B",
        "equora-slate-dark": "#475569",
        "equora-slate-muted": "#94A3B8",
        "equora-border": "#E2E8F0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "sidebar-width": "280px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "stack-lg": "32px",
        "margin-desktop": "48px",
        "stack-sm": "8px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-xl": ["Inter", "sans-serif"],
        code: ["Inter", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        code: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

