packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bufferutil: true
  esbuild: true
  keccak: true
  prisma: true
  puppeteer: true
  secp256k1: true
  utf-8-validate: true

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "bufferutil"
  - "esbuild"
  - "keccak"
  - "prisma"
  - "puppeteer"
  - "secp256k1"
  - "utf-8-validate"
