import { ethers, deployments } from "hardhat";
import * as fs from "fs";
import * as path from "path";

/**
 * generateTsAbis.ts
 * Reads all deployed contract artifacts and generates a typed TypeScript
 * file (deployedContracts.ts) in the Next.js frontend's contracts/ directory.
 *
 * This runs automatically after `yarn deploy` via the hardhat-deploy plugin.
 */
async function generateTsAbis() {
  const { get } = deployments;

  const contracts = [
    { name: "BTitanRegistry", alias: "BTitanRegistry" },
    { name: "BTitanDAO",      alias: "BTitanDAO" },
    { name: "BTitanMatrix",   alias: "BTitanMatrix" },
    { name: "BTitanNFT",      alias: "BTitanNFT" },
    { name: "BTitanVestingVault", alias: "BTitanVestingVault" },
    { name: "MockToken",      alias: "BTitanToken" }, // aliased to BTitanToken on local
  ];

  const network = await ethers.provider.getNetwork();
  const chainId = network.chainId.toString();

  const contractsData: Record<string, { address: string; abi: any[] }> = {};

  for (const { name, alias } of contracts) {
    try {
      const deployment = await get(name);
      contractsData[alias] = {
        address: deployment.address,
        abi: deployment.abi,
      };
      console.log(`✅ ${alias}: ${deployment.address}`);
    } catch {
      // Contract not deployed (e.g. BTitanToken on local where MockToken is used)
      console.log(`⏭️  ${name} not found, skipping...`);
    }
  }

  const output = `/**
 * This file is auto-generated by scripts/generateTsAbis.ts after running yarn deploy.
 * Do NOT edit manually — your changes will be overwritten.
 * Last generated: ${new Date().toISOString()}
 */
import { GenericContractsDeclaration } from "../utils/scaffold-eth/contract";

const deployedContracts = {
  ${chainId}: ${JSON.stringify(contractsData, null, 4).replace(/"([^"]+)":/g, '"$1":')}
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

  // Output path: packages/nextjs/contracts/deployedContracts.ts
  const outputPath = path.resolve(__dirname, "../../nextjs/contracts/deployedContracts.ts");

  // Ensure directory exists
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output, "utf-8");

  console.log(`\n📄 deployedContracts.ts written to: ${outputPath}`);
}

generateTsAbis()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
